version: '3.7'
services:
    algo-testnet:
        build:
            context: .
        restart: always
        volumes:
            - ./data:/root/node/data
        tty: true
        ports:
            - "8080:8080"
            - "4001:4001"
